version: '3.8'
services:
  spring-server:
    image: shyeonpk/jenkins-test
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
